name: Test
on:
  workflow_call:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Check Flagsmith key
        if: always()
        run: echo ${{secrets.FLAGSMITH_KEY}}
      - name: Install dependencies
        run: npm ci
      - name: Check formatting errors
        run: npm run format
      - name: Check for ESLINT Errors
        run: npm run lint
      - name: Check for Type errors
        run: npm run typecheck
      - name: Build Project
        env:
          FLAGSMITH_KEY: ${{secrets.FLAGSMITH_KEY}}
        run: |
          echo $FLAGSMITH_KEY
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: .next/
      - name: Run Unit tests
        run: npm run test
      - uses: actions/upload-artifact@v4
        #to run even if test failed
        if: always()
        with:
          name: coverage
          path: coverage/
      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        id: cache-playwright
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: |
          npx playwright install
      - name: Run E2E Tests
        env:
          FLAGSMITH_KEY: ${{secrets.FLAGSMITH_KEY}}
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
      - name: Send a Slack Message on Failure
        uses: slackapi/slack-github-action@v1.24.0
        if: failure()
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🛑 *<https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}|${{ github.workflow }} workflow run>* failed."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
